title: Sysli na Vinici English
description: >-
  Monitoring and rescue of European ground squirrel populations in the Czech
  Republic and awarding winemakers with 'Sysli na Vinici' stamp for supporting
  sousliks in their vineyards.
url: 'https://en.syslinavinici.cz'
logo: /media/sysli_na_vinici_logo_200.jpg
lang: en_GB
lang_alternatives:
  - icon: /assets/images/flag_cz.png
    label: Přepnout na češtinu
    title: 'Navštivte českou verzi této stránky: %@'
    url: 'https://www.syslinavinici.cz'
    lang: en_GB
author: alka-wildlife
facebook:
  admins: 1133305906
  app_id: 145375228868712
  publisher: 269120446533000
social:
  links:
    - 'http://bit.ly/alkawildlifeEN'
    - 'http://bit.ly/alkawildlifeFB'
    - 'http://bit.ly/alkawildlifeIN'
    - 'http://bit.ly/alkawildlifeTW'
    - 'http://bit.ly/alkawildlifeYT'
  name: 'ALKA Wildlife, o.p.s.'
webmaster_verifications:
  google: o27dsTgYww0bzXVmTZ_CgadoY8QtzpDMgo-bVSgH3OM
google_analytics: UA-65760369-2
