source: en_GB
destination: _site.en_GB

title: Sysli na vinici
description: >-
  Záchrana sysla obecného v naší krajině a podpora vinařů, kteří na
  svých vinohradech sysla mají.
baseurl: ""
url: https://www.syslinavinici.cz
author: alka-wildlife
lang_alternatives:
- lang: en_GB
  label: Přepnout na češtinu
  title: "Navštivte českou verzi této stránky: %@"
  url: https://www.syslinavinici.cz
  icon: /assets/images/flag_cz.png

# Integrations and machine-readable metadata
facebook:
  app_id: 145375228868712
  publisher: 269120446533000
  admins: 1133305906
logo: /media/sysli_na_vinici_logo_200.jpg
social:
  name: ALKA Wildlife, o.p.s.
  links:
    - https://www.facebook.com/AlkaWildlife
webmaster_verifications:
  google: o27dsTgYww0bzXVmTZ_CgadoY8QtzpDMgo-bVSgH3OM
lang: en_GB
google_analytics: UA-65760369-2
kramdown:
  smart_quotes: 0x0201A,0x02018,0x0201E,0x0201C
