---
backend:
  name: git-gateway
  branch: master

media_folder: uploads

collections:
- name: galleries
  label: Galleries
  label_singular: Gallery
  folder: _galleries
  create: true
  fields:
  - name: page
    label: Page
    widget: string
  meta:
  - name: date
    label: Created at
    widget: date
    format: YYYY-MM-DD HH:mm:ss ZZ

- name: posts
  label: News
  description: News on your project or website
  folder: _posts
  locomotive_name: news
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  create: true
  fields:
  - name: title
    label: Title
    widget: string
  - name: image
    label: Image
    widget: image
  - name: body
    label: Content
    widget: markdown
    locomotive_name: content
  - name: published
    label: Published
    widget: boolean
    default: true
  - name: date
    label: Published at
    widget: date
    format: YYYY-MM-DD
    locomotive_name: published_at

- name: showcases
  label: Showcases
  label_singular: Showcase
  description: Big photos that are displayed on the homepage
  folder: _showcases
  create: true
  fields:
  - name: image
    label: Image
    widget: image
  meta:
  - name: date
    label: Created at
    widget: date
    format: YYYY-MM-DD HH:mm:ss ZZ

- name: user_answers
  label: User answers
  label_singular: User answer
  description: Answers to user questions that are displayed in counselling section
  folder: _user_answers
  create: true
  fields:
  - name: title
    label: Title
    widget: string
  - name: author
    label: Author
    widget: string
  - name: date
    label: Published at
    widget: date
    format: YYYY-MM-DD
    locomotive_name: published_at
  - name: body
    label: Content
    widget: markdown
    locomotive_name: content
  - name: categories
    label: Categories
    widget: list
    required: false

- name: user_questions
  label: User questions
  label_singular: User question
  description: Questions that are sent from users from counselling section.
  folder: _user_questions
  create: true
  fields:
  - name: name
    label: Name
    widget: string
  - name: email
    label: Email
    widget: string
  - name: body
    label: Message
    widget: markdown
    locomotive_name: message
  meta:
  - name: date
    label: Created at
    widget: date
    format: YYYY-MM-DD HH:mm:ss ZZ

- label: Site Settings
  name: settings
  files:
    - label: Authors
      label_singular: Author
      name: authors
      file: _data/authors.yml
      fields: []

- name: photos
  label: Photos
  label_singular: Photo
  description: Photos in photogallery
  folder: _photos
  create: true
  fields:
  - name: title
    label: Title
    widget: string
  - name: image
    label: Image
    widget: image
  - name: home_thumbnail
    label: Thumbnail for home page (113 × 103 px)
    widget: image
  - name: gallery_thumbnail
    label: Thumbnail for gallery (250 × 250 px)
    widget: image
  - name: content_thumbnail
    label: Thumbnail for gallery as part of a page (200 × 200 px)
    widget: image
  - name: body
    label: Description
    widget: markdown
    required: false
    locomotive_name: description
  - name: author
    label: Author
    widget: string
    required: false
  - name: categories
    label: Categories
    widget: list
    required: false
  - name: galleries
    label: Gallery
    widget: relation
    collection: galleries
    searchFields:
    - page
    valueField: slug
    required: false
  meta:
  - name: date
    label: Created at
    widget: date
    format: YYYY-MM-DD HH:mm:ss ZZ
